// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: ftp.proto

package T2

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Chunk_Info
	//	*Chunk_Chunk
	Data isChunk_Data `protobuf_oneof:"data"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_ftp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_ftp_proto_rawDescGZIP(), []int{0}
}

func (m *Chunk) GetData() isChunk_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Chunk) GetInfo() *BookData {
	if x, ok := x.GetData().(*Chunk_Info); ok {
		return x.Info
	}
	return nil
}

func (x *Chunk) GetChunk() []byte {
	if x, ok := x.GetData().(*Chunk_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isChunk_Data interface {
	isChunk_Data()
}

type Chunk_Info struct {
	Info *BookData `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type Chunk_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*Chunk_Info) isChunk_Data() {}

func (*Chunk_Chunk) isChunk_Data() {}

type BookData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sender string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BookData) Reset() {
	*x = BookData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookData) ProtoMessage() {}

func (x *BookData) ProtoReflect() protoreflect.Message {
	mi := &file_ftp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookData.ProtoReflect.Descriptor instead.
func (*BookData) Descriptor() ([]byte, []int) {
	return file_ftp_proto_rawDescGZIP(), []int{1}
}

func (x *BookData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *BookData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BookData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ChunkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ChunkResponse) Reset() {
	*x = ChunkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkResponse) ProtoMessage() {}

func (x *ChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ftp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkResponse.ProtoReflect.Descriptor instead.
func (*ChunkResponse) Descriptor() ([]byte, []int) {
	return file_ftp_proto_rawDescGZIP(), []int{2}
}

func (x *ChunkResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChunkResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_ftp_proto protoreflect.FileDescriptor

var file_ftp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x66, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x66, 0x74, 0x70,
	0x22, 0x4c, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x66, 0x74, 0x70, 0x2e, 0x42, 0x6f,
	0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x16,
	0x0a, 0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52,
	0x05, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4a,
	0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x0d, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x42,
	0x67, 0x5a, 0x65, 0x2f, 0x72, 0x75, 0x6e, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x6c, 0x65,
	0x6f, 0x61, 0x72, 0x63, 0x6f, 0x2f, 0x39, 0x34, 0x41, 0x43, 0x38, 0x38, 0x38, 0x42, 0x41, 0x43,
	0x38, 0x38, 0x36, 0x41, 0x31, 0x36, 0x2f, 0x53, 0x65, 0x6d, 0x65, 0x73, 0x74, 0x72, 0x65, 0x5f,
	0x65, 0x6e, 0x5f, 0x63, 0x61, 0x73, 0x69, 0x74, 0x61, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x73, 0x64,
	0x65, 0x2f, 0x49, 0x4e, 0x46, 0x33, 0x34, 0x33, 0x2d, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61,
	0x73, 0x2d, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x2f, 0x54,
	0x61, 0x72, 0x65, 0x61, 0x73, 0x2f, 0x54, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ftp_proto_rawDescOnce sync.Once
	file_ftp_proto_rawDescData = file_ftp_proto_rawDesc
)

func file_ftp_proto_rawDescGZIP() []byte {
	file_ftp_proto_rawDescOnce.Do(func() {
		file_ftp_proto_rawDescData = protoimpl.X.CompressGZIP(file_ftp_proto_rawDescData)
	})
	return file_ftp_proto_rawDescData
}

var file_ftp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ftp_proto_goTypes = []interface{}{
	(*Chunk)(nil),         // 0: ftp.Chunk
	(*BookData)(nil),      // 1: ftp.BookData
	(*ChunkResponse)(nil), // 2: ftp.ChunkResponse
}
var file_ftp_proto_depIdxs = []int32{
	1, // 0: ftp.Chunk.info:type_name -> ftp.BookData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ftp_proto_init() }
func file_ftp_proto_init() {
	if File_ftp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ftp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ftp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChunkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ftp_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Chunk_Info)(nil),
		(*Chunk_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ftp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ftp_proto_goTypes,
		DependencyIndexes: file_ftp_proto_depIdxs,
		MessageInfos:      file_ftp_proto_msgTypes,
	}.Build()
	File_ftp_proto = out.File
	file_ftp_proto_rawDesc = nil
	file_ftp_proto_goTypes = nil
	file_ftp_proto_depIdxs = nil
}
